language: ruby

cache:
  - bundler

os:
  - linux
  - osx

rvm:
 - 2.0
 - 2.1
 - 2.2.2

before_install:
  - gem build dutiful.gemspec
  - gem install dutiful-*.gem

notifications:
  email:
    on_success: never
    on_failure: change
