[application]
name = 'RubyMine'

[[file]]
path = 'Library/Application Support/RubyMine60'

[[file]]
path = 'Library/Preferences/RubyMine60'

[[file]]
path = 'Library/Application Support/RubyMine70'

[[file]]
path = 'Library/Preferences/RubyMine70'

